apiVersion: v1
kind: Service
metadata:
  name: dobby-svc-lb
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
      app: dobby-pod
  ports:
  - protocol: TCP
    port: 4444
    targetPort: 4444