-
  name: "ping test"
  hosts: myec2
  tasks:
    -
      name: "test connectivity"
      ping:    
    - 
      name: create a file in ec2
      command: touch /home/centos/demo2.txt
    - 
      name: append a file in ec2
      shell: |
        echo "first line" >> /home/centos/demo2.txt
    - 
      name: run a script to print date
      script: date.sh
    