FROM maven:3.8.6-openjdk-8 AS build
WORKDIR /usr/app
COPY pom.xml /usr/app/
RUN mvn dependency:go-offline -B
COPY src /usr/app/src
RUN mvn package -DskipTests

FROM adoptopenjdk/openjdk8
COPY --from=build /usr/app/target/metadata-service.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar", "app.jar"]
